# Generated by Django 3.2.3 on 2021-12-01 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20211130_0716'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='likes',
            new_name='liked',
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.ManyToManyField(blank=True, related_name='contents', to='posts.PostFileContent'),
        ),
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tags', to='posts.Tag'),
        ),
    ]
