# Generated by Django 3.2.3 on 2021-12-06 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_post_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={},
        ),
    ]
